[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["ffmpeg", "python311"]

[build.nixpacksPlan.phases.install]
cmds = ["pip3 install -r backend/requirements.txt"]

[deploy]
startCommand = "cd backend && gunicorn --workers 1 --timeout 7200 --worker-class sync --bind 0.0.0.0:$PORT app:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
